version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    environment:
      ENV: "local"
      PORT: ":8000"
      AUTH_CONFIG_URL: "${AUTH_CONFIG_URL}"
      AUTH_AUDIENCE: "${AUTH_AUDIENCE}"
      ENABLE_SWAGGER: true
      DB_CONNECTION_STRING: "host=db user=postgres password=${POSTGRES_PASSWORD} dbname=goapitemplate port=5432"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: goapitemplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend
volumes:
  data:
networks:
  backend: