name: deploy-aks
description: Test

inputs:
  azure_credentials:
    description: Credentials to login to Azure
    required: true
  azure_resource_group:
    description: Resource Group name where AKS is deployed
    required: true
  azure_cluster_name:
    description: AKS cluster name
    required: true
  image_id:
    description: Image name and tag to deploy
    required: true
  auth_config_url:
    description: Open ID configuration URL
    required: true
  auth_audience:
    description: Valid audience for this API
    required: true
  db_connection_string:
    description: Connection string for the DB. Connection string format depends on db_provider parameter.
    required: true
  postgres_db:
    description: Postgres DB name.
    required: true
  postgres_user:
    description: Postgres DB user.
    required: true
  postgres_password:
    description: Postgres DB user password.
    required: true

runs:
  using: "composite"
  steps:
  - name: Azure login
    id: login
    uses: azure/login@v1.4.3
    with:
      creds: ${{ inputs.azure_credentials }}

  - name: Set AKS context
    id: set-context
    uses: azure/aks-set-context@v3
    with:
      resource-group: '${{ inputs.azure_resource_group }}' 
      cluster-name: '${{ inputs.azure_cluster_name }}'

  - name: Setup kubectl
    id: install-kubectl
    uses: azure/setup-kubectl@v3
  
  - uses: azure/k8s-create-secret@v2
    with:
      namespace: 'default'
      secret-type: 'generic'
      secret-name: app-secrets
      string-data: '{"AUTH_CONFIG_URL": "${{ inputs.auth_config_url }}", "AUTH_AUDIENCE": "${{ inputs.auth_audience }}", "DB_CONNECTION_STRING": "${{ inputs.db_connection_string }}"}'

  - uses: azure/k8s-create-secret@v2
    with:
      namespace: 'default'
      secret-type: 'generic'
      secret-name: db-secrets
      string-data: '{"POSTGRES_DB": "${{ inputs.postgres_db }}", "POSTGRES_USER": "${{ inputs.postgres_user }}", "POSTGRES_PASSWORD": "${{ inputs.postgres_password }}"}'

  - name: Deploy to AKS
    id: deploy-aks
    uses: Azure/k8s-deploy@v4
    with:
      namespace: 'default'
      manifests: |
          ./kubernetes/db-pvc.yaml
          ./kubernetes/db-pv.yaml
          ./kubernetes/db-deployment.yaml
          ./kubernetes/db-service.yaml
          ./kubernetes/app-configmap.yaml
          ./kubernetes/app-deployment.yaml
          ./kubernetes/app-service.yaml
      images: '${{ inputs.image_id }}'