// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID         int32
	Name       string
	Email      string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	UpdateUser string
}
