apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: web-app
data:
  ENV: "aks"
  WEB_PORT: ":8000"
  AUTH_CLAIMS: "given_name,family_name"
  AUTH_SCOPES: "api"
  ENABLE_SWAGGER: "true"
  ALLOWED_ORIGIN: "*"