name: ci-plain

# on:
#   push:
#     branches:
#       - "main"

on: workflow_dispatch

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0

      - name: Pull dependencies
        run: go mod download

      - name: Build
        run: go build goapi-template

      - name: Test
        run: go test -cover ./... > test-result.txt

      - name: Pull request comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: test-result.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            goapi-template
            auth/*.rego