name: ci-plain

# on:
#   push:
#     branches:
#       - "main"

permissions:
  pull-requests: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_validate:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0

      - name: Pull dependencies
        run: go mod download

      - name: Build
        run: go build goapi-template

      - name: Test
        run: go test -cover ./... > test-result.txt

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
    
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Pull request comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: test-result.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            goapi-template
            auth/*.rego
  
  deploy:
    if: github.event_name == 'push'
    needs: [build_validate]
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: gorest-template
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./dist

    # Azure logout 
      - name: logout
        run: |
          az logout